### ISSUE TITLE
Octave compatibility

### ISSUE THREAD

**Issue by samos123** [adikhosla/feature-extraction#1]
I tried to run it on octave without much success yet. 

The following issues I noticed, most of them I already fixed while keeping the Matlab function as before. Pull request will be made soon as soon as I get demo.m working
1. Can't compile and getting this error from conf.m:
   error: 'RandStream' undefined near line 51 column 10
   error: called from:
   error:   feature-extraction/util/conf.m at line 51, column 8
   error:   feature-extraction/demo.m at line 20, column 3
2. Octave doesn't have the RandStream function
3. There is no matlabpool in Octave
4. feature-extraction/util/batch_feature.m at line 59, column error: save: Unrecognized option '-v7.3'

**Comment by andjimrio** [comment]
Thanks you for your contribution! I had used RandStream but it is not compatible with Octave yet. After seeing your code, I used rand and it works!
