### ISSUE TITLE
Info about Classifiers

### ISSUE THREAD

**Issue by mastiffs92** [adikhosla/feature-extraction#6]
Hi,
I have seen that in the demo.m file there is a part about the svm if i uncomment it doesn't work, giving me :Length of label vector does not match # of instances.

**Comment by adikhosla** [comment]
Hi, thank you for your interest in this repository! The demo does not use any SVM library - it uses a simple nearest neighbor approach. That error sounds like it might be coming from sp_dist2.

**Comment by mastiffs92** [comment]
thank you for the answer.
